version: "3.7"

services:

  engine:
    image: dtitov/cloud-watch-engine:latest
    ports:
    - "8080:8080"
    volumes:
    - ${PWD}/engine/config/config.yml:/cloud-watch/engine/config/config.yml

  web:
    image: dtitov/cloud-watch-web:latest
    ports:
    - "80:8080"
