---
swagger: '2.0'
info:
  description: |
    API for the cloud-watch client
  version: 1.0.0
  title: Cloud Watch
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: MIT
    url: URL

basePath: /v1

tags:
- name: vms
  description: Everything about your VMS
  externalDocs:
    description: Find out more
    url: http://swagger.io

paths:
  /tenants:
    get:
      operationId: api.tenants.get
      tags:
      - vms
      summary: Finds all tenants
      description: Gives a list of all tenants, with information about names, regions and clould provider.
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Vm'
        400:
          description: Invalid status value

definitions:
  Tenant:
    type: object
    properties:
      id:
        type: string
      provider:
        type: string
      region:
        type: string
  Vm:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      creation_time:
        type: string
        format: date-time
